// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Carbon:language': typeof import('~icons/carbon/language')['default']
    'Carbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
    'Ic:outlinePlus': typeof import('~icons/ic/outline-plus')['default']
    'MaterialSymbols:arrowBackIosNew': typeof import('~icons/material-symbols/arrow-back-ios-new')['default']
    'MaterialSymbols:edit': typeof import('~icons/material-symbols/edit')['default']
    'MaterialSymbols:link': typeof import('~icons/material-symbols/link')['default']
    'MaterialSymbols:linkOff': typeof import('~icons/material-symbols/link-off')['default']
    'Mdi:dotsVertical': typeof import('~icons/mdi/dots-vertical')['default']
    'SimpleIcons:1password': typeof import('~icons/simple-icons/1password')['default']
    'SimpleIcons:google': typeof import('~icons/simple-icons/google')['default']
    'SimpleIcons:twitter': typeof import('~icons/simple-icons/twitter')['default']
  }
}

export { }
